<?php
/**
 * SQLite Database Connection Class - Auto-generated by Setup
 */
class Database {
    private static $instance = null;
    private $connection;
    
    private $database_path = __DIR__ . '/../ludo_realtime.db';
    
    private function __construct() {
        try {
            $this->connection = new PDO(
                'sqlite:' . $this->database_path,
                null,
                null,
                [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC
                ]
            );
            
            // SQLite-spezifische Einstellungen
            $this->connection->exec('PRAGMA foreign_keys = ON');
            $this->connection->exec('PRAGMA journal_mode = WAL');
            $this->connection->exec('PRAGMA synchronous = NORMAL');
            
        } catch (PDOException $e) {
            throw new Exception('SQLite connection failed: ' . $e->getMessage());
        }
    }
    
    public static function getInstance() {
        if (self::$instance === null) {
            self::$instance = new self();
        }
        return self::$instance;
    }
    
    public function getConnection() {
        return $this->connection;
    }
    
    public function getDatabasePath() {
        return $this->database_path;
    }
}
?>